background1_color: '#f2949c'
background2_color: '#ffc3eb'
border_color: '#......'
button1_color: '#915966'
button2_color: '#cb7086'
footer_color: '#......'
frame1_color: '#f2c1bd'
frame2_color: '#f2c1bd'
frame3_color: '#f2c1bd'
header_color: '#eb9ab9'
negative_color: '#FFFFFF'
placeholder_color: '#FFFFFF'
positive_color: '#FFFFFF'
random_name_length: 20
resize_mode: adjust
text1_color: '#000000'
text2_color: '#FFFFFF'
unusable_button_color: '#FFFFFF'
